### ISSUE TITLE
False idle splasher notification

### ISSUE THREAD

**Issue by DaraTheGreat** [pajlads/runelite-pickpocket-helper#14]
People have reported that sometimes the plugin notifies them that the splasher is idle even though the splasher is still there. I believe this is caused by the splasher switching weapons or accounts. Ill further explain why we (splashers) do those two things. 

     1: Switching Weapons: Sometimes the knight will step out from the corner of the bank and you can use a dragon spear special attack to get the knight  back into the corner.
     
     2. Switching Accounts: To avoid the 6 hour logout timer, you can stop splashing on one account and start spam clicking on another account. There is a 1 tick window where you can grab the aggro of the knight. Then you log out and back in and do the same thing again to regain aggro on the original account.

If the plugin would wait for at least 5 ticks before sending this notification, I think this problem would be fixed. If you can do this, however, I would make it 8-10 ticks just to be safe. Thanks! <3

**Comment by iProdigy** [comment]
Currently the plugin waits 7 ticks since the last splashing animation started: https://github.com/pajlads/runelite-pickpocket-helper/blob/37a8519563500f2634feef1ba82e53918d559e27/src/main/java/com/pickpockethelper/entity/Splasher.java#L47

Since the casting speed is 5 ticks, I guess it's more like 2 ticks of grace period

I'll make a quick PR to increase this pr

**Comment by iProdigy** [comment]
This change should be published to the plugin hub now
